NAME=Dynamic / Matugen
MODE=dark

ACCENT=#d4bbfc
SELECTION=#4b4357
MUTED=#cbc4cf

BACKGROUND=#151218
DARK_BACKGROUND=#151218
DARKER_BACKGROUND=#0f0d13
LIGHTER_BACKGROUND=#2c292f

FOREGROUND=#e7e0e8
DARK_FOREGROUND=#948e99
LIGHT_FOREGROUND=#cbc4cf
BRIGHT_FOREGROUND=#e7e0e8

RED=#ffb4ab
YELLOW=#dcb291
ORANGE=#f1b7c4
GREEN=#adc892
CYAN=#cec2db
BLUE=#d4bbfc
MAGENTA=#f1b7c4
BROWN=#a0797f

BRIGHT_RED=#fabbb5
BRIGHT_YELLOW=#ddbaa0
BRIGHT_GREEN=#b7cca1
BRIGHT_CYAN=#d2c7dd
BRIGHT_BLUE=#d7c1f8
BRIGHT_MAGENTA=#efbeca

SURFACE=#211f24
ICON_THEME=auto
