NAME=Dynamic / Matugen
MODE=dark

ACCENT=#b2d189
SELECTION=#404a33
MUTED=#c5c8ba

BACKGROUND=#12140e
DARK_BACKGROUND=#12140e
DARKER_BACKGROUND=#0d0f09
LIGHTER_BACKGROUND=#282b24

FOREGROUND=#e2e3d8
DARK_FOREGROUND=#8f9285
LIGHT_FOREGROUND=#c5c8ba
BRIGHT_FOREGROUND=#e2e3d8

RED=#ffb4ab
YELLOW=#d3b871
ORANGE=#a0d0cb
GREEN=#a3ce72
CYAN=#c0cbac
BLUE=#b2d189
MAGENTA=#a0d0cb
BROWN=#96805c

BRIGHT_RED=#f9bcb3
BRIGHT_YELLOW=#d5bf83
BRIGHT_GREEN=#aed184
BRIGHT_CYAN=#c6cfb3
BRIGHT_BLUE=#bad497
BRIGHT_MAGENTA=#abd3cd

SURFACE=#1e201a
ICON_THEME=auto
