//! Qt6 Widgets-paletta a qt6ct-hez, elsosorban a Hyprland portal valasztojahoz.

use crate::theme::palette::Palette;
use crate::theme::render::{Vars, load_template, render, write_if_changed};
use crate::theme::{color, paths};
use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

const BUILTIN: &str = include_str!("../../../templates/qt6ct-colors.conf.tmpl");
const PORTAL_DROPIN: &str = "# Generated by vellum_shell. Do not edit.\n\
[Service]\n\
Environment=QT_QPA_PLATFORMTHEME=qt6ct\n";

pub fn generate(palette: &Palette) -> Result<Option<(PathBuf, bool)>> {
    let qt6ct_dir = paths::config_dir().join("qt6ct");
    let output = qt6ct_dir.join("colors/vellum.conf");
    let template = load_template("qt6ct-colors.conf.tmpl", BUILTIN);
    let palette_changed = write_if_changed(&output, &render(&template, &vars(palette)))?;

    // A share-picker az xdg-desktop-portal-hyprland gyereke, nem az OBS-e. A
    // drop-in csak ennek a szolgaltatasnak adja at a qt6ct platformtemat, igy
    // nem irjuk felul a felhasznalo osszes tobbi Qt alkalmazasanak stilusat.
    let dropin = paths::config_dir()
        .join("systemd/user/xdg-desktop-portal-hyprland.service.d/vellum-qt6ct.conf");
    let dropin_changed = write_if_changed(&dropin, PORTAL_DROPIN)?;

    let mut config_changed = false;
    if crate::theme::side_effects_enabled() {
        config_changed = configure(&qt6ct_dir.join("qt6ct.conf"), &output)?;

        if palette_changed || dropin_changed || config_changed {
            crate::proc::run_quiet("systemctl", &["--user", "daemon-reload"], crate::proc::SHORT);
            crate::proc::run_quiet(
                "systemctl",
                &["--user", "restart", "xdg-desktop-portal-hyprland.service"],
                crate::proc::LONG,
            );
        }
    }

    Ok(Some((output, palette_changed || dropin_changed || config_changed)))
}

/// A qt6ct QPalette-listaja a Qt ColorRole sorrendjet koveti. A telepitett
/// qt6ct 21 erteket var (WindowText..PlaceholderText); az Accent szerepet a
/// Highlightbol szarmaztatja.
fn vars(palette: &Palette) -> Vars {
    let background = palette.color(&["BACKGROUND"], "#1e1e2e");
    let foreground = palette.color(&["FOREGROUND"], "#cdd6f4");
    let accent = palette.color(&["ACCENT", "BORDER_FOREGROUND"], "#89b4fa");
    let surface = palette.color(&["SURFACE", "LIGHTER_BACKGROUND"], "#181825");
    let muted = palette.color(&["MUTED", "DARK_FOREGROUND"], "#9399b2");
    let selection = palette.color_opt(&["SELECTION"]).unwrap_or_else(|| accent.clone());
    let base = palette
        .color_opt(&["DARK_BACKGROUND"])
        .unwrap_or_else(|| color::mix(&background, &surface, 70));
    let shadow = palette
        .color_opt(&["DARKER_BACKGROUND"])
        .unwrap_or_else(|| color::mix(&base, "#000000", 75));
    let bright = palette.color_opt(&["BRIGHT_FOREGROUND"]).unwrap_or_else(|| foreground.clone());
    let link_visited = palette.color_opt(&["MAGENTA"]).unwrap_or_else(|| accent.clone());
    let highlighted_text =
        if color::luminance(&selection) >= 145 { background.clone() } else { foreground.clone() };

    let light = color::mix(&surface, &foreground, 75);
    let midlight = color::mix(&surface, &foreground, 88);
    let mid = color::mix(&surface, &muted, 65);
    let alternate = color::mix(&base, &surface, 55);

    let active = colors(&[
        (&foreground, 0xff),
        (&surface, 0xff),
        (&light, 0xff),
        (&midlight, 0xff),
        (&base, 0xff),
        (&mid, 0xff),
        (&foreground, 0xff),
        (&bright, 0xff),
        (&foreground, 0xff),
        (&base, 0xff),
        (&background, 0xff),
        (&shadow, 0xff),
        (&selection, 0xff),
        (&highlighted_text, 0xff),
        (&accent, 0xff),
        (&link_visited, 0xff),
        (&alternate, 0xff),
        (&foreground, 0xff),
        (&surface, 0xff),
        (&foreground, 0xff),
        (&muted, 0x80),
    ]);

    let disabled = colors(&[
        (&muted, 0xff),
        (&surface, 0xff),
        (&light, 0xff),
        (&midlight, 0xff),
        (&base, 0xff),
        (&mid, 0xff),
        (&muted, 0xff),
        (&bright, 0xff),
        (&muted, 0xff),
        (&base, 0xff),
        (&background, 0xff),
        (&shadow, 0xff),
        (&selection, 0xff),
        (&muted, 0xff),
        (&accent, 0xff),
        (&link_visited, 0xff),
        (&alternate, 0xff),
        (&muted, 0xff),
        (&surface, 0xff),
        (&muted, 0xff),
        (&muted, 0x80),
    ]);

    let mut vars = Vars::new();
    vars.insert("ACTIVE_COLORS".into(), active.clone());
    vars.insert("DISABLED_COLORS".into(), disabled);
    vars.insert("INACTIVE_COLORS".into(), active);
    vars
}

fn colors(entries: &[(&str, u8)]) -> String {
    entries.iter().map(|(color, alpha)| argb(color, *alpha)).collect::<Vec<_>>().join(", ")
}

fn argb(value: &str, alpha: u8) -> String {
    format!("#{alpha:02x}{}", value.trim_start_matches('#'))
}

fn configure(config: &Path, scheme: &Path) -> Result<bool> {
    let before = std::fs::read(config).ok();
    let config_text = config.to_string_lossy();
    let scheme_text = scheme.to_string_lossy();
    for (key, value) in [("color_scheme_path", scheme_text.as_ref()), ("custom_palette", "true")] {
        let result = crate::proc::run(
            "kwriteconfig6",
            &["--file", config_text.as_ref(), "--group", "Appearance", "--key", key, value],
            crate::proc::SHORT,
        )
        .with_context(|| format!("a qt6ct nem allithato be ({key})"))?;
        if !result.status.success() {
            bail!("a kwriteconfig6 elutasitotta a qt6ct {key} beallitasat");
        }
    }

    Ok(before.as_deref() != std::fs::read(config).ok().as_deref())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scheme_has_every_qt6ct_color_role() {
        let palette = Palette::parse(
            "BACKGROUND=#111111\nFOREGROUND=#eeeeee\nACCENT=#80a0ff\n\
             SURFACE=#222222\nMUTED=#777777\nSELECTION=#334466\n",
        );
        let vars = vars(&palette);

        for key in ["ACTIVE_COLORS", "DISABLED_COLORS", "INACTIVE_COLORS"] {
            let colors: Vec<_> = vars[key].split(", ").collect();
            assert_eq!(colors.len(), 21, "{key}: {colors:?}");
            assert!(colors.iter().all(|value| value.len() == 9 && value.starts_with('#')));
        }
        assert!(vars["ACTIVE_COLORS"].contains("#ff80a0ff"));
        assert!(vars["ACTIVE_COLORS"].contains("#80777777"));
    }
}
